# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscribed',
            field=models.ManyToManyField(related_name='courses_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
