# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='files.File')),
            ],
        ),
    ]
